import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class YouTubeVideo {
  final String id;
  final String title;
  final String channelName;
  final String thumbnailUrl;
  final String? duration;
  final String? viewCount;
  final int rawViewCount;
  final String? description;

  const YouTubeVideo({
    required this.id,
    required this.title,
    required this.channelName,
    required this.thumbnailUrl,
    this.duration,
    this.viewCount,
    this.rawViewCount = 0,
    this.description,
  });

  String get watchUrl => 'https://www.youtube.com/watch?v=$id';
}

class YouTubeService {
  // Broad trending AI queries to get popular results
  static const _queries = [
    'AI news',
    'artificial intelligence',
    'ChatGPT',
    'OpenAI',
    'machine learning',
    'AI update',
  ];

  /// Minimum views to be considered "trending"
  static const _minViews = 10000;

  static Future<List<YouTubeVideo>> fetchTrendingAI({int maxResults = 5}) async {
    final yt = YoutubeExplode();
    try {
      final candidates = <YouTubeVideo>[];
      final seen = <String>{};

      for (final query in _queries) {
        try {
          // Search last week, sorted by view count
          final results = await yt.search.search(query,
            filter: UploadDateFilter.lastWeek);

          for (final v in results.take(10)) {
            if (seen.contains(v.id.value)) continue;
            seen.add(v.id.value);

            final views = v.engagement.viewCount;

            // Skip low-view videos
            if (views < _minViews) continue;

            // Skip live streams
            if (v.isLive) continue;

            final thumbUrl = v.thumbnails.highResUrl.isNotEmpty
                ? v.thumbnails.highResUrl
                : v.thumbnails.standardResUrl;

            String? duration;
            if (v.duration != null) {
              final d = v.duration!;
              if (d.inHours > 0) {
                duration = '${d.inHours}:${(d.inMinutes % 60).toString().padLeft(2, '0')}:${(d.inSeconds % 60).toString().padLeft(2, '0')}';
              } else {
                duration = '${d.inMinutes}:${(d.inSeconds % 60).toString().padLeft(2, '0')}';
              }
            }

            candidates.add(YouTubeVideo(
              id: v.id.value,
              title: v.title,
              channelName: v.author,
              thumbnailUrl: thumbUrl,
              duration: duration,
              viewCount: _formatViews(views),
              rawViewCount: views,
              description: v.description,
            ));
          }
        } catch (_) {}
      }

      // Sort by highest views first
      candidates.sort((a, b) => b.rawViewCount.compareTo(a.rawViewCount));

      // Return top N
      return candidates.take(maxResults).toList();
    } finally {
      yt.close();
    }
  }

  static String _formatViews(int? views) {
    if (views == null || views == 0) return '';
    if (views >= 1000000) return '${(views / 1000000).toStringAsFixed(1)}M views';
    if (views >= 1000) return '${(views / 1000).toStringAsFixed(0)}K views';
    return '$views views';
  }

  /// Fetch closed captions transcript from YouTube video.
  /// Tries English first, then auto-generated, then any available track.
  static Future<String> _fetchTranscript(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest = await yt.videos.closedCaptions.getManifest(videoId);
      if (manifest.tracks.isEmpty) return '';

      // Prefer English, then auto-generated English, then first available
      ClosedCaptionTrackInfo? track;
      track = manifest.tracks.cast<ClosedCaptionTrackInfo?>().firstWhere(
        (t) => t!.language.code.startsWith('en') && !t.isAutoGenerated,
        orElse: () => null,
      );
      track ??= manifest.tracks.cast<ClosedCaptionTrackInfo?>().firstWhere(
        (t) => t!.language.code.startsWith('en'),
        orElse: () => null,
      );
      track ??= manifest.tracks.first;

      final captionTrack = await yt.videos.closedCaptions.get(track);
      final text = captionTrack.captions.map((c) => c.text).join(' ');
      return text;
    } catch (_) {
      return '';
    } finally {
      yt.close();
    }
  }

  static Future<String> summarizeVideo(YouTubeVideo video) async {
    const apiKey = String.fromEnvironment('ANTHROPIC_API_KEY');
    if (apiKey.isEmpty) throw Exception('ANTHROPIC_API_KEY not configured');

    // Try to get transcript first, fall back to description
    String transcript = '';
    try {
      transcript = await _fetchTranscript(video.id);
    } catch (_) {}

    String context;
    if (transcript.length > 100) {
      // Use transcript (cap at 2000 chars to stay within token limits)
      final trimmed = transcript.length > 2000
          ? transcript.substring(0, 2000)
          : transcript;
      context = 'Title: ${video.title}\nChannel: ${video.channelName}\n\nTranscript:\n$trimmed';
    } else {
      // Fall back to description
      final desc = video.description?.trim() ?? '';
      context = desc.isNotEmpty
          ? 'Title: ${video.title}\n\nDescription: ${desc.length > 800 ? desc.substring(0, 800) : desc}'
          : 'Title: ${video.title}\nChannel: ${video.channelName}';
    }

    final prompt =
        'Summarize this YouTube video about AI/ML in exactly 3 concise bullet points. '
        'Each bullet point should start with "• ". No other formatting.\n\n$context';

    final response = await http.post(
      Uri.parse('https://api.anthropic.com/v1/messages'),
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: json.encode({
        'model': 'claude-haiku-4-5',
        'max_tokens': 200,
        'messages': [{'role': 'user', 'content': prompt}],
      }),
    ).timeout(const Duration(seconds: 30));

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      final contentList = data['content'] as List?;
      if (contentList == null || contentList.isEmpty) {
        throw Exception('Empty response from AI');
      }
      return (contentList[0]['text'] as String?) ?? 'Summary unavailable';
    } else {
      throw Exception('AI service error: ${response.statusCode}');
    }
  }
}
